name: Trigger auto deployment for mcp-mvp1-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mcp-mvp1-api-AutoDeployTrigger-cec519c0-1258-45b6-9c03-6886e8c58111.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MCPMVP1API_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MCPMVP1API_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MCPMVP1API_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: mcpmvp1acr.azurecr.io
          registryUsername: ${{ secrets.MCPMVP1API_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MCPMVP1API_REGISTRY_PASSWORD }}
          containerAppName: mcp-mvp1-api
          resourceGroup: MCP-MVP1
          imageToBuild: mcpmvp1acr.azurecr.io/mcp-mvp1-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


